<a href="https://colab.research.google.com/github/ManasviAtGitHub/Algorithms-for-Optimization/blob/main/PyTorch_01_Dealing_with_Tensors_and_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using torch.tensor()

In [4]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
## matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

Why so?
You initialize neural networks through random numbers

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers(until the model is trained and this numbers represents weights in the model)


In [26]:
# Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4074, 0.1359, 0.6109, 0.2607],
        [0.5923, 0.0980, 0.1219, 0.2160],
        [0.7697, 0.1283, 0.1708, 0.8725]])

In [27]:
random_tensor.ndim,  random_tensor.shape

(2, torch.Size([3, 4]))

In [28]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.0633, 0.6118, 0.2396, 0.8726],
         [0.5385, 0.5859, 0.5558, 0.4189],
         [0.8843, 0.5093, 0.2525, 0.5787]]])

In [29]:
random_tensor.ndim,  random_tensor.shape

(3, torch.Size([1, 3, 4]))

### Zeroes and Ones

In [36]:
# create a tensor of all zeros
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
zeroes.dtype ## default data type

torch.float32

In [38]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [39]:
# use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# creating tensors like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.2],
                               dtype = None, # what datatype is the tensor (eg. float32, float16...)
                               device = None, # what device your tensor is on (cpu or gpu)
                               requires_grad= None, # wheether or not to track gradients with this tensors operations
                               )

float_32_tensor

tensor([3.0000, 6.0000, 9.2000])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3.0000, 6.0000, 9.2031], dtype=torch.float16)

In [44]:
#attributes of tensors
print(f"Datatype of tensor : {float_16_tensor.dtype}")
print(f"Shape of tensor : {float_16_tensor.shape}")
print(f"Device tensor is on : {float_16_tensor.device}")

Datatype of tensor : torch.float16
Shape of tensor : torch.Size([3])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [45]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [47]:
# subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [49]:
## trying built-in functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [51]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

### Matrix Multiplication

* Element wise
* Dot product

Rules for multiplication (Dot product)

**Inner dimensions must match**
* (3,2) @ (3,2) => Err
* (3,2) @ (2,3) => Will work
* (2,3) @ (3,2) => Will work

**Outer dimensions results as output**
* (3,2) @ (2,3) => (3,3)
* (2,3) @ (3,2) => (2,2)


In [52]:
print(f"{tensor} * {tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [53]:
# element-wise
tensor * tensor

tensor([1, 4, 9])

In [54]:
# dot product
torch.matmul(tensor, tensor)

tensor(14)

In [55]:
tensor @ tensor

tensor(14)

In [59]:
tensorA = torch.tensor ([[1,2,3],[4,5,6]])
tensorB = torch.tensor ([[10,20,30],[40,50,60]])

In [60]:
tensorA.shape, tensorB.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [61]:
torch.mm(tensorA, tensorB) ## To resolve this, use transpose to match dimension)

RuntimeError: ignored

In [62]:
tensorB.T

tensor([[10, 40],
        [20, 50],
        [30, 60]])

In [63]:
torch.mm(tensorA, tensorB.T)

tensor([[140, 320],
        [320, 770]])